# Generated by Django 2.1.4 on 2018-12-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('status', models.CharField(max_length=1)),
                ('progress', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
