# Generated by Django 2.1.4 on 2019-01-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=20, verbose_name='Слово')),
                ('imagew', models.ImageField(height_field=307, upload_to='cards/', width_field=512)),
                ('soundw', models.FileField(upload_to='files/')),
                ('transcr', models.CharField(max_length=20, verbose_name='Транскрипция')),
                ('imaget', models.ImageField(height_field=307, upload_to='cards/', width_field=512)),
                ('soundt', models.FileField(upload_to='files/')),
                ('interpret', models.CharField(max_length=20, verbose_name='Перевод')),
                ('example1', models.CharField(max_length=200)),
                ('sounde1', models.FileField(upload_to='files/')),
                ('example2', models.CharField(max_length=200)),
                ('sounde2', models.FileField(upload_to='files/')),
                ('explain', models.TextField(verbose_name='Пояснение')),
            ],
        ),
    ]
