# Generated by Django 2.1.4 on 2018-12-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='word',
            name='published_date',
        ),
    ]
