# Generated by Django 2.1.4 on 2019-01-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='imaget',
            field=models.ImageField(upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='imagew',
            field=models.ImageField(upload_to='cards/'),
        ),
    ]
