# Generated by Django 2.1.4 on 2019-01-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190102_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='soundt',
        ),
        migrations.AddField(
            model_name='word',
            name='association',
            field=models.CharField(default='', max_length=20, verbose_name='Ассоциация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='imaget',
            field=models.ImageField(upload_to='cards/', verbose_name='Образ звучания'),
        ),
        migrations.AlterField(
            model_name='word',
            name='imagew',
            field=models.ImageField(upload_to='cards/', verbose_name='Образ слова'),
        ),
        migrations.AlterField(
            model_name='word',
            name='soundw',
            field=models.FileField(upload_to='files/', verbose_name='Звучание слова'),
        ),
    ]
